In [3]:

from create_groups import create_groups

n = 100 # number of inputs (synapses)
m = 2 # number of groups
k = 20 # number of cells in each group
groups, remaining = create_groups(n, m, k)

print(groups)
print(remaining)


[[37, 76, 87, 11, 18, 96, 44, 3, 16, 90, 27, 46, 73, 10, 4, 81, 84, 66, 80, 7], [60, 91, 82, 57, 74, 24, 21, 42, 50, 43, 72, 71, 22, 89, 61, 86, 65, 62, 31, 9]]
[1, 2, 5, 6, 8, 12, 13, 14, 15, 17, 19, 20, 23, 25, 26, 28, 29, 30, 32, 33, 34, 35, 36, 38, 39, 40, 41, 45, 47, 48, 49, 51, 52, 53, 54, 55, 56, 58, 59, 63, 64, 67, 68, 69, 70, 75, 77, 78, 79, 83, 85, 88, 92, 93, 94, 95, 97, 98, 99, 100]


In [4]:
import numpy as np
list_lists = np.zeros(10, dtype=list)
list_lists[0] = [1,2,3]
list_lists[5] = [4,5,6]
print(list_lists)


[list([1, 2, 3]) 0 0 0 0 list([4, 5, 6]) 0 0 0 0]


In [13]:
from create_groups_probabilities import generate_random_vector

vec = generate_random_vector([0.1, 0.9], 30)

print(vec)

[2 2 1 2 2 2 2 2 2 1 1 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 1 2 1 2]


In [46]:

import numpy as np
import random

numbers = [1, 2, 4]
random.shuffle(numbers)
print("Randomized vector", numbers)
n_groups = 4
n_synapses = 10
# Create a binary matrix with n rows and L columns
remain_matrix = np.zeros((len(numbers), n_synapses), dtype=int)

# Set the value 1 at the specific positions
for idx, num in enumerate(numbers):
    if 0 <= num < n_synapses:
        remain_matrix[idx, num] = 1

# Display the binary matrix
print("The remaining matrix", remain_matrix)

groups_matrix = np.zeros((n_groups, n_synapses), dtype=int)
for group, row in enumerate(groups):
    # set 1 in binary matrix indexes of the group values
    groups_matrix[group, row] = 1

print("The group matrix", groups_matrix)

# concatenate the two matrices
input_matrix = np.concatenate((groups_matrix, remain_matrix), axis=0)  

print("The input matrix", input_matrix)




Randomized vector [4, 2, 1]
The remaining matrix [[0 0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]]
The group matrix [[0 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 0]
 [0 1 1 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 1 0 1 1]]
The input matrix [[0 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 0]
 [0 1 1 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 1 0 1 1]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]]


In [33]:
n_groups = len(range(0, 100, 20))
n_remaining = len(range(0, 6, 2))

print(range(n_groups + n_remaining))
for sequence in range(n_groups + n_remaining):
    print(sequence)


range(0, 8)
0
1
2
3
4
5
6
7


In [9]:
n_groups = 4
n_synapses = 10
groups = [[1, 2, 3, 4], [4, 5, 6], [1,2], [2,4,6,8,9]]

binary_matrix = np.zeros((n_groups, n_synapses), dtype=int)
for group, row in enumerate(groups):
    # set 1 in binary matrix indexes of the group values
    binary_matrix[group, row] = 1

print(binary_matrix)


[[0 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 0]
 [0 1 1 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 1 0 1 1]]


In [6]:
from create_groups_probabilities import generate_random_vector
dt = 0.1
dt_bin = 10

group_probabilities = [0.5, 0.1, 0.4]
bin_activation_vector = generate_random_vector(group_probabilities,int(dt_bin/dt))
print(bin_activation_vector)


[1 3 1 1 3 1 3 3 2 1 2 2 3 3 1 1 1 1 1 3 1 1 1 3 3 1 1 3 3 1 1 3 2 1 1 3 2
 1 1 1 3 1 3 3 3 1 1 3 1 1 3 3 3 1 1 1 1 1 1 2 1 3 3 1 3 1 1 3 2 3 1 1 3 3
 1 2 1 1 1 3 1 1 3 3 3 2 3 1 1 1 1 1 2 3 3 3 1 1 1 1]


In [10]:
import numpy as np
n_synapses = 10
group_vector = np.zeros((1, n_synapses), dtype=int)
print(groups[1])
group_vector[groups[1]] = 1
print(group_vector)

IndexError: index 4 is out of bounds for axis 0 with size 1